/**
 * Tiny re-export shim so component files don't have to know about lucide-react
 * directly. Centralised here in case we later swap icon libraries.
 */

export {
  AlertOctagon,
  AlertTriangle,
  Activity,
  ArrowDown,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  BadgeCheck,
  Bell,
  BookOpen,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Clock,
  Construction,
  Download,
  ExternalLink,
  FileText,
  Folder,
  FolderOpen,
  FolderUp,
  Gauge,
  HelpCircle,
  Inbox,
  LayoutDashboard,
  Library,
  Loader2,
  MessageSquare,
  MessagesSquare,
  Microscope,
  Plus,
  RotateCcw,
  Search,
  Settings,
  ShieldAlert,
  Sparkles,
  TrendingUp,
  Upload,
  User,
  Wrench,
  X,
} from "lucide-react";
